services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SIGNER_KEY=${JWT_SIGNER_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID}
      - PAYOS_API_KEY=${PAYOS_API_KEY}
      - PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_MAIL_URL=${BREVO_MAIL_URL}
      - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    ports:
      - "8080:8080"
    container_name: spring-app-container
    restart: unless-stopped